version: '3.7'

services:

  front:
    build: ./Front
    depends_on:
      - db
    volumes:
      - ./Front:/usr/share/nginx/html
    networks:
      - MarkOSnet

  generador:
    build: ./GeneradorDatos
    # ports:
    #   - 3000:80
    volumes:
      - ./GeneradorDatos:/app
    depends_on:
      - db
    networks:
      - MarkOSnet

  laravel1:
    build: ./api
    # command: php artisan migrate:fresh --seed
    image: laravel.prod
    volumes:
      - ./api:/src/app
    # ports:
    #   - 8000:80
    depends_on:
      - db
    networks:
      - MarkOSnet

  laravel2:
    build: ./api
    # command: php artisan migrate:fresh --seed
    image: laravel.prod
    volumes:
      - ./api:/src/app
    # ports:
    #   - 8000:80
    depends_on:
      - db
    networks:
      - MarkOSnet
  db:
    image: mysql
    command: --max_allowed_packet=325058560
    environment: 
      MYSQL_ROOT_PASSWORD: stocks
      MYSQL_USER: stocks
      MYSQL_DATABASE: stocks
      MYSQL_PASSWORD: stocks
    volumes: 
      - ./dump:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - MarkOSnet

  phpmyadmin:
          depends_on:
              - db
          image: 'phpmyadmin/phpmyadmin:latest'
          restart: always
          environment:
              PMA_HOST: db
              PMA_PORT: 3306
              PMA_USER: 'stocks'
              PMA_PASSWORD: 'stocks'
          networks:
              - MarkOSnet
          ports:
              - 83:80
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - MarkOSnet
    depends_on:
      - laravel1
      - laravel2
networks:
    MarkOSnet:
        driver: bridge
volumes:
    mysql:
        driver: local