version: '3.7'

services:
  db:
    image: mysql
    command: --max_allowed_packet=325058560
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: stocks
      MYSQL_USER: stocks
      MYSQL_DATABASE: stocks
      MYSQL_PASSWORD: stocks
    volumes: 
      - /mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - MarkOSnet

  phpmyadmin:
          depends_on:
              - db
          image: 'phpmyadmin/phpmyadmin:latest'
          environment:
              PMA_HOST: db
              PMA_PORT: 3306
              PMA_USER: 'stocks'
              PMA_PASSWORD: 'stocks'
          networks:
              - MarkOSnet
          ports:
              - 8000:80
networks:
    MarkOSnet:
        driver: bridge
  # volumes:
  #     sail-mysql:
  #         driver: local